### ISSUE TITLE
Access to all chests on multiple maps

### ISSUE THREAD

**Issue by Theridgeback** [JamesPeters98/ChestsPlusPlus#7]
I currently host a server at home for my son and his friends,
It runs on an apple mac using spigot  minecraft and works flawlessly.
I they have a choice of a few maps depending on what they want to play, 
So they can have an island map or a mountain map or savanah ect,ect.
All i do is copy over the server.properties file from the map to the root directory, boot the server and off they go.

However I have two issues that I have found.
If they create a chest set on the island, called [IslandHome] they can put whatever they want in this chest, it works.
If they are playing on the Mountain  one, they can do exactly the same, [MountainHome],
however they have found that if they use the chestlink menu command they can access all of their chests, which isnt a bad thing as you could just create a chest with a sign anyway to access these items. 

However this includes the chests that are not currently on the game they are playing.

So if they were on the mountain one and had found a mine they could store all the track in there and then access all of this track from there island map. 
Is there a way to stop this?

The only way i can think of is to change the save folder location of the chests.yml file and rather than have it in the root of the server store it in the folder directory of the map, that way whatever map you have loaded the chest file is loaded from the map folder with the same name that way you can only access this set of chests.

Failing that its a case of backing up and restoring the chest.yml each time from the map folders

Secondly, when there is a sign on the chest the other players cant open it, but if they break the sign they can then open this chest. Any ideas on stopping this one?

Many thanks

Mac.

**Comment by JamesPeters98** [comment]
Hey!

So, currently the chests.yml is server-wide so that chests are accessible from the Nether and the End. In the current version your best bet is to just rename the chests.yml for each of the maps and change it every time you start a new map. Or maybe just have 3 different instances of the server folder that contain the different maps, that way you won't have to change the server.properties file each time either. I may add a property to the config in the next version of the plugin that lets you define the path/name of the chests.yml file. (I already hate that the first location I chose was the root directory for the chests.yml file)

For your second problem, when someone breaks a sign that should break the ChestLink and if there was only one chest left in that group those items will be placed into that chest or spill onto the ground if there was any overflow. If there are multiple chests that are part of that group the chest will simply just become a default empty chest, that anyone can open - which is vanilla behaviour.

**Comment by JamesPeters98** [comment]
Hey, are you still having issues with this?

**Comment by Theridgeback** [comment]
Hi James,

I got around it by storing the chest.yml file into the folder of the island that we are currently using, and copying it back when we play that island.
When we finish it gets copied back to the island
That way any chests that are created only go to the island that is being played.

Thanks anyway.

Mac.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by JamesPeters98** [comment]
Cool glad you found a solution!
